// Fetch headers builder
// Execute with bun: wrangler dev

import {
  CONNECTION_KEEP_ALIVE,
  DEFAULT_ACCEPT,
  DEFAULT_ACCEPT_ENCODING,
  DEFAULT_ACCEPT_LANGUAGE,
  DEFAULT_USER_AGENT,
  HEADER_ACCEPT,
  HEADER_ACCEPT_ENCODING,
  HEADER_ACCEPT_LANGUAGE,
  HEADER_CONNECTION,
  HEADER_REFERER,
  HEADER_SEC_FETCH_DEST,
  HEADER_SEC_FETCH_MODE,
  HEADER_SEC_FETCH_SITE,
  HEADER_SEC_FETCH_USER,
  HEADER_UPGRADE_INSECURE_REQUESTS,
  HEADER_USER_AGENT,
  SEC_FETCH_DEST_DOCUMENT,
  SEC_FETCH_MODE_NAVIGATE,
  SEC_FETCH_SITE_NONE,
  SEC_FETCH_USER_TRUE,
  UPGRADE_INSECURE_TRUE,
} from '../constants.ts';

// Build fetch headers with browser-like values
export const buildFetchHeaders = (targetOrigin: string): Record<string, string> => ({
  [HEADER_USER_AGENT]: DEFAULT_USER_AGENT,
  [HEADER_ACCEPT]: DEFAULT_ACCEPT,
  [HEADER_ACCEPT_LANGUAGE]: DEFAULT_ACCEPT_LANGUAGE,
  [HEADER_ACCEPT_ENCODING]: DEFAULT_ACCEPT_ENCODING,
  [HEADER_REFERER]: targetOrigin,
  [HEADER_CONNECTION]: CONNECTION_KEEP_ALIVE,
  [HEADER_UPGRADE_INSECURE_REQUESTS]: UPGRADE_INSECURE_TRUE,
  [HEADER_SEC_FETCH_DEST]: SEC_FETCH_DEST_DOCUMENT,
  [HEADER_SEC_FETCH_MODE]: SEC_FETCH_MODE_NAVIGATE,
  [HEADER_SEC_FETCH_SITE]: SEC_FETCH_SITE_NONE,
  [HEADER_SEC_FETCH_USER]: SEC_FETCH_USER_TRUE,
});
